spring: 
  profiles:
  active:
    - dev
--- 
server:
  port: 8001

spring: 
  profiles: dev
  application: 
    name: microservicecloud-config-client-provider

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.78.101:3306/cloudDB01
    username: root
    password: Fei130823.

  dbcp2:
    min-idle: 5
    initial-size: 5
    max-total: 5
    max-wait-millis: 200 

mybatis:
  type-aliases-package: com.springcloud.api.entity
  mapper-locations: classpath:mapper/**.xml

eureka: 
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: provider-8001.com
    prefer-ip-address: true

info:
  app.name: microservicecloud-provider
  company.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$


---
server:
  port: 8001

spring: 
  profiles: test
  application: 
    name: microservicecloud-config-client-provider

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.78.101:3306/cloudDB01
    username: root
    password: Fei130823.

  dbcp2:
    min-idle: 5
    initial-size: 5
    max-total: 5
    max-wait-millis: 200  

mybatis:
  type-aliases-package: com.springcloud.api.entity
  mapper-locations: classpath:mapper/**.xml

eureka: 
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: provider-8001.com
    prefer-ip-address: true

info:
  app.name: microservicecloud-provider
  company.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$